session = {};
session.current_project_xml = "";
session.current_project_folder = "";
session.current_active_file = "";
editors = {};
tabs = [];
localStorage.haxeHint = new Array();  
settings = {};
settings.autosave_for_autocomplete = true;
